### PR TITLE
Select web driver

### LINKED ISSUE #1: Support for other browsers than firefox
Currently only Firefox is supported. Allow to configure the browser.

### PR DESCRIPTION
**Pull request by sclassen**
Add 'geb.driver' parameter to allow configuration of web driver implementation.

This will resolve #1.

### CODE REVIEW

**Comment by sclassen** [comment]
@mojavelinux I somehow lost permissions on the screenshot repo. I think I kicked myself out of the screenshot team. Could you help me getting the permissions back. thx.

**Comment by mojavelinux** [comment]
Fixed!

**Comment by ambition-consulting** [comment]
@sclassen why no merge?

I currently get [this](http://stackoverflow.com/questions/37693106/selenium-2-53-not-working-on-firefox-47) great error for firefox, would love to change the driver to chrome.

**Comment by sclassen** [comment]
Because of the error you are getting I discovered that setting the variable `geb.driver` is not sufficient for some of the drivers. They need more configuration. I am having a look at making usage of the [geb environment mechanism](http://www.gebish.org/manual/current/#environment-sensitivity) to allow for more flexibility. Hopefully I will find some time to do this in the next days.

**Comment by sclassen** [comment]
I did some researching today. Here the outcome:
- using `geb.driver` is very limiting in that it does not allow to configure the driver and only 4 driver classes are supported
- using the geb configuration. This is the most flexible approach. One can configure almost every aspect of geb. There are 2 drawbacks
  - one needs to include the config file in the classpath of asciidoctorj
  - one cannot change the browser during conversion of an asciidoc file
- using `geb.env` does not gain much benefit over the plain configuration. The way `geb.env` works is that it effects the loading of the config file. Once the file is loaded changing `geb.env` has no effect.

It looks to me as if using the geb configuration is the simplest and most flexible approach.
I will try to write some examples to show how this can be setup.

**Comment by stoeps13** [comment]
I try to implement screenshot or geb within my asciidoc, but building oens just Firefox and then I get a timeout (newer FF problem with selenium).

Any hint or example how to use geb with chromedriver? "it can handle a groovy script" is not that helpful when you have no clue from groovy. ;) 

Tried the continous-documentation code from Alex Soto too, but no luck either. 

Thanks in advance.

**Comment by sclassen** [comment]
New version 0.2.0 released. The new version does no longer include Firefox Webdriver.
Instead the webdriver for your browser needs to be specified in your build script.

See https://github.com/sclassen/asciidoctorj-screenshot-example for both gradle and maven example

**Pull request closed without merging**
