### PR TITLE
expands document attribute in screenshots

### PR DESCRIPTION
**Pull request by lordofthejars**

### CODE REVIEW

**Comment by sclassen** [comment]
This would fix issue #3

**Comment by sclassen** [comment]
@lordofthejars could you extract the logic to a trait so it could be re-used in the GebBlockProcessor.
The trait could then also be tested independent of the processors (and maybe even be the base for a asciidcotorj update).

**Comment by lordofthejars** [comment]
According to Dan https://github.com/asciidoctor/asciidoctorj-screenshot/issues/3 it is not necessary to do it for block attributes.

**Comment by sclassen** [comment]
OK, now I get even more confused. I will write some tests next week to understand where attributes get expanded...

**Comment by lordofthejars** [comment]
ok, since versions are free, can we merge this PR and release a new version, and if what Dan suggests doesn't work we can open a new issue. WDYT?

**Comment by sclassen** [comment]
will release 0.1.1 tonight

**Comment by lordofthejars** [comment]
Great!! Thanks tomorrow I will be able to write an article about it then :D
thank you so much.

El dj., 14 abr. 2016 a les 16:43, sclassen (notifications@github.com) va
escriure:

**Pull request merged**
